PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/2af17da334e652062dd74aa74c8763bb08ff444f

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...2af17da334e652062dd74aa74c8763bb08ff444f

2af17da334 (HEAD, origin/master) boards/sim:  Add a TCP loopback test.
ac4e6618bb arch/mips: Clear the software interrupt through a common function implemented in the chip specific code.
90043390ff arch/mips/: Fix architectures' references in Kconfigs and Toolchain.defs.
0dc1dc605d arch/mips: When a CPU implements an External Interrupt Controller, use the IPL bits to control masking interrupts.
d68693f74c drivers/telnet: Stop the loop if SIGSTP char is match and SIGINT not enabled
7ec66ccf94 Get the full directory name of the testbuild.sh no matter where called from
d09af3b7f3 Run .c and .h files modified by PR241 through nxstyle.
f2f385902b arch/sim: Remove the unnecessary file guard
7fd3a3bcca xarch/sim: Call pm_initialize from up_initialize directly
978575d79a arch/sim: Pass X11 related config to host environment

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/539d0854dda738d4338f711ad7516e110e88b761

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...539d0854dda738d4338f711ad7516e110e88b761

539d0854 (HEAD -> master, origin/master) examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m
2f4b309b gs2200m: Retry indefinately on GS2200M_IOC_ASSOC failure